config/routes.rb
Filesys::Application.routes.draw do
  
  resources :buckets
 
  
  
  
 match '/showf', to: 'folders#show'
  match '/new', to: 'folders#new'
  
  match '/deldir', to: 'folders#delete'
  match '/rename', to: 'folders#rename'
  match '/deletefile', to: 'folders#deletefile'
  match '/new_file', to: 'folders#new_file'
  match '/delete', to: 'files#delete'
  match '/create', to: 'files#create'
  match '/show', to: 'files#show'
  
 








   
    root :to => 'folders#show'


end

app/models/bucket.rb
class Bucket < ActiveRecord::Base
  attr_accessible :name
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name
  
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include FoldersHelper
      
  
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buckets }
    end
  end

  # GET /buckets/1
  # GET /buckets/1.json
  def show
    @bucket = Bucket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bucket }
    end
  end

  # GET /buckets/new
  # GET /buckets/new.json
  def new
    @bucket = Bucket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bucket }
    end
  end

  # GET /buckets/1/edit
  def edit
    @bucket = Bucket.find(params[:id])
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(params[:bucket])

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
        format.json { render json: @bucket, status: :created, location: @bucket }
      else
        format.html { render action: "new" }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buckets/1
  # PUT /buckets/1.json
  def update
    @bucket = Bucket.find(params[:id])

    respond_to do |format|
      if @bucket.update_attributes(params[:bucket])
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket = Bucket.find(params[:id])
    @bucket.destroy

    respond_to do |format|
      format.html { redirect_to buckets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  
  rescue_from Errno::EACCES, :with => :error_render_method
  rescue_from Errno::ENOENT, :with => :error_render_method3
 
   
  def error_render_method
        
      render :action => 'new_folder' 
      flash[:error] = 'Access Denied Pls Change Path.'
      
  end
  
  
  def error_render_method3   
           render :action => 'new' 
           
   end
    
  def create # create new file
     @fpath = params[:fpath]
     
     if @fpath
    
      
     FileUtils.touch("#{@fpath}")
     flash[:notice] = "New File Created Successfully"
     render '_newfile'
    
     else
       flash[:notice] = "New File Not Created"
       render 'create'
       
    end
  end
   
   
  def show #method called when file is opened
   
 end
 
  def delete # delete file
   @f_name = params[:fname]
   
   if FileUtils.rm(@f_name)
     
     flash[:success] = "Deleted Successful"
      redirect_to :back
   else
     flash[:error] = "Folder Contains sub Folder or files."
     redirect_to :back
   end
   
 end
 
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  
  #Errno::EACCES in FoldersController#new 
  #Errno::ENOTEMPTY in FoldersController#deldir 
    
  rescue_from Errno::EACCES, :with => :error_render_method
  rescue_from  Errno::ENOTEMPTY , :with => :error_render_method2
  rescue_from Errno::ENOENT, :with => :error_render_method3
 
   
  def error_render_method
        
      render :action => 'new_folder' 
      flash[:error] = 'Access Denied Pls Change Path.'
      
  end
  
  def error_render_method2

    
    flash[:error] = 'Folder Contails sub Folder or files.'
       redirect_to :back 
      flash[:error] = 'Folder Contains sub Folder or files.'
   
  end

  def error_render_method3   
           render :action => 'createfolder' 
           
   end
    
   
    
  def show  #listing from given path
   @fpath = params[:fpath]
     
     if @fpath
       
      @files =  Dir[ "#{@fpath}"+"/*"]    
      render '_form'
    else
      flash[:error] = "Invalid Path"
      render 'show'
      
    end
   
  end
  
    
  def new #calls new folder name input page
 @f_path =params[:fpath]
 
     if FileUtils.mkdir_p("#{@f_path}")
        render '_nform'
        flash[:success] = "Folder Created"
        
    else 
       flash[:error] = "Folder notCreated"
        render 'new'
     end
      
  end

 
  def delete #delete directory
         @f_name = params[:fname]
         
   if Dir.rmdir(@f_name)
     flash[:success] = "Deleted Successful"
      redirect_to :back
   else
     flash[:error] = "Folder Contains sub Folder or files."
     redirect_to :back
   end
   
    
    
  end
  
  def rename #rename 
    
    pat = params[:fpath].slice(0..(params[:fpath].index('/')))
    
   if FileUtils.mv(params[:fpath],pat + params[:newname])
    flash[:notice] = "Rename Successfull"
    redirect_to :back
    else
     flash[:notice] = "Invalid Name"
    redirect_to :back 
    end
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
  
  
end

app/views/buckets/_form.html.erb
<%= form_for(@bucket) do |f| %>
  <% if @bucket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
      <% @bucket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing bucket</h1>

<%= render 'form' %>

<%= link_to 'Show', @bucket %> |
<%= link_to 'Back', buckets_path %>

app/views/buckets/index.html.erb
<h1>Listing buckets</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buckets.each do |bucket| %>
  <tr>
    <td><%= bucket.name %></td>
    <td><%= link_to 'Show', bucket %></td>
    <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
    <td><%= link_to 'Destroy', bucket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bucket', new_bucket_path %>

app/views/buckets/new.html.erb
<h1>New bucket</h1>

<%= render 'form' %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bucket.name %>
</p>


<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %>

app/views/files/_newfile.html.erb
<%= flash[:error] %>

<h1>File Created Successfully</h1>


 
  	
 

<h3><%= link_to 'Back', folders_path %></h3>

app/views/files/create.html.erb
<h2>Enter new file path and name</h2>

<%= form_tag :controller => "files", :action => 'create'  do %>
    
    <%= text_field_tag(:fpath,params[:fpath]) %>
    <%= submit_tag("Submit", :name => nil) %>
    <% end %>


</div>


<%= link_to 'Back', folders_path %>

app/views/files/new_file.html.erb
<h2>Enter new file path and name</h2>

<%= form_tag :controller => "folders", :action => 'new_file'  do %>
    
    <%= text_field_tag(:fpath,params[:fpath]) %>
    <%= submit_tag("Submit", :name => nil) %>
    <% end %>


</div>


<%= link_to 'Back', folders_path %>

app/views/files/open_file1.html.erb
<h1><%= flash[:error] %></h1>
<h1><%= flash[:success] %></h1>


<pre>
<h3><%= render :file => params[:flpath] %></h3>
</pre>

app/views/files/show.html.erb
<h1><%= flash[:error] %></h1>
<h1><%= flash[:success] %></h1>


<pre>
<h3><%= render :file => params[:flpath] %></h3>
</pre>

app/views/folders/_form.html.erb
<h1><%= flash[:error] %></h1>
<h1><%= flash[:success] %></h1>
<h1><%= flash[:notice] %></h1>

<h1>Listing folders</h1>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <div class="list">
  
  <% @files.each do |file| %>
  <tr>
  	<% if File.directory?(file)%>
  	<td><%= file %></td>
  
  <td> <%= form_tag showf_path , :method => 'get'   do %>
 	
    <%= hidden_field_tag(:fpath,file) %>
    
    <%= submit_tag("Open Folder", :name => nil) %>
    <% end %></td>
  
 <td> <%= button_to "Delete Folder", {:controller => "folders", :action => 'delete', :fname => file }, :confirm => "Are you sure ?", :method => :delete %> </td>
  
 <td><%= form_tag rename_path   do %>
 	
    <%= hidden_field_tag(:fpath,file) %>
    <%= text_field_tag(:newname) %>
    <%= submit_tag("Rename", :name => nil,:confirm => "Are you sure ?") %>
    <% end %></td>

  	<% else %>
    <td><%= file %></td>
   
   
   <td><%= form_tag show_path   do %>
 	
    <%= hidden_field_tag(:flpath,file) %>    
    <%= submit_tag("Open", :name => nil) %>
    <% end %></td>
    
    <td> <%= button_to "Delete File", {:controller => "files", :action => 'delete', :fname => file }, :confirm => "Are you sure ?", :method => :delete %> </td>
    
    <td><%= form_tag rename_path   do %>
 	
    <%= hidden_field_tag(:fpath,file) %>
    <%= text_field_tag(:newname) %>
    <%= submit_tag("Rename", :name => nil,:confirm => "Are you sure ?") %>
    <% end %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
</div>

<h3><%= link_to 'New Folder', new_path %>
	<%= link_to 'New File', create_path %>
</h3>

app/views/folders/_nform.html.erb
<%= flash[:error] %>

<h1>Folder Created Successfully</h1>


 
  	
 

<h3><%= link_to 'Back', folders_path %></h3>

app/views/folders/_sfsorm.html.erb
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <div class="list">
  	
  <% @files.each do |file| %>
  <tr>
  	<% if File.directory?(file)%>
  	<td><%= file %></td>
  
  <td> <%= button_to "Open Folder", {:controller => "folders", :action => 'subflist', :q => file }  %> </td>
  
 <td> <%= button_to "Delete Folder", {:controller => "folders", :action => 'deld', :fid => file }, :confirm => "Are you sure ?", :method => :delete %> </td>
  
 <td><%= form_tag renam_path   do %>
 	
    <%= hidden_field_tag(:q,file) %>
    <%= text_field_tag(:rn) %>
    <%= submit_tag("Renam", :name => nil,:confirm => "Are you sure ?") %>
    <% end %></td>

  	<% else %>
    <td><%= file %></td>
   <td><%= form_tag opfile_path   do %>
 	
    <%= hidden_field_tag(:x,file) %>
    
    <%= submit_tag("Open", :name => nil) %>
    <% end %></td>
    <td> <%= button_to "Delete File", {:controller => "folders", :action => 'deld', :fid => file }, :confirm => "Are you sure ?", :method => :delete %> </td>
    <td><%= form_tag renam_path   do %>
 	
    <%= hidden_field_tag(:q,file) %>
    <%= text_field_tag(:rn) %>
    <%= submit_tag("Renam", :name => nil,:confirm => "Are you sure ?") %>
    <% end %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
</div>

<h3><%= link_to 'New Folder', nf_path %>
	<%= link_to 'New File', newf_path %>
</h3>

app/views/folders/createfolder.html.erb
<h1>New folder</h1>

<h2>Enter new folder path and name</h2>

<%= form_tag :controller => "folders", :action => 'new'  do %>
    
    <%= text_field_tag(:fpath,params[:fpath]) %>
    <%= submit_tag("Submit", :name => nil) %>
    <% end %>


</div>


<%= link_to 'Back', folders_path %>

app/views/folders/deld.html.erb
<h1>Folder Deleted</h1>






<h3>
<%= link_to 'Back', folders_path %>
</h3>

app/views/folders/deldir.html.erb
<h1>Folder Deleted</h1>






<h3>
<%= link_to 'Back', folders_path %>
</h3>

app/views/folders/edit.html.erb
<h1>Editing folder</h1>

<%= render 'form' %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<h1><%= flash[:notice] %></h1>
<h1>Listing folders</h1>

<div>
<%= form_tag folders_path , :method => 'get'  do %>    
    <%= text_field_tag(:fpath,params[:fpath]) %>
    <%= submit_tag("Submit Path", :name => nil) %>
    <% end %>


</div>


<!-- <div class="new_folder">
<h3><%= link_to 'New Folder', new_folder_path %>
</h3> -->
</div>

app/views/folders/new.html.erb
<h1>New folder</h1>


<%= render '_nform'  %>

</div>


<%= link_to 'Back', folders_path %>

app/views/folders/new_folder.html.erb
<%= flash[:error] %>


<h1>New folder</h1>

<h2>Enter new folder path and name</h2>

<%= form_tag new_folder_path , :method => 'get'  do %>
    
    <%= text_field_tag(:q,params[:q]) %>
    <%= submit_tag("Submit", :name => nil) %>
    <% end %>


</div>


<%= link_to 'Back', folders_path %>

app/views/folders/newf.html.erb
<h1>New folder</h1>

<h2>Enter new file path and name</h2>

<%= form_tag :controller => "folders", :action => 'newf' , :method => 'get'  do %>
    
    <%= text_field_tag(:q,params[:q]) %>
    <%= submit_tag("Submit", :name => nil) %>
    <% end %>


</div>


<%= link_to 'Back', folders_path %>

app/views/folders/path.html.erb

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<div class="list">
	<% path("public/*")%>
  <% @files.each do |file| %>
  <tr>
  	<% if File.directory?(file)%>
  	<td><%= file %></td>
  <td><%= link_to 'Open Folder', file[/\/.*/] %></td>
  	<% else %>
    <td><%= file %></td>
    <td><%= link_to 'Open', file[/\/.*/] %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
</div>

app/views/folders/show.html.erb
<h1><%= flash[:notice] %></h1>
<h1>Listing folders</h1>

<div>
<%= form_tag showf_path , :method => 'get'  do %>    
    <%= text_field_tag(:fpath,params[:fpath]) %>
    <%= submit_tag("Submit Path", :name => nil) %>
    <% end %>


</div>


<!-- <div class="new_folder">
<h3><%= link_to 'New Folder', new_folder_path %>
</h3> -->
</div>

app/views/folders/subflist.html.erb
<h1>Listing folders</h1>


<%= render 'sfsorm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filesys</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>